# spring:
#   datasource:
#     url: jdbc:postgresql://host.docker.internal:5432/contactdb
#     username: gaurav
#     password: pass123
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.PostgreSQLDialect

# jwt:
#   secret: thisisaverysecretkeythatshouldbe32bytesmin
#   expiration-ms: 3600000

# server:
#   port: 8080

server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}
